---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-grafana
  labels:
    app: grafana
spec:
  storageClassName: "freenas-nfs-csi"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
